name: conopot
description: A new Flutter project.

publish_to: 'none'
version: 1.4.1+63

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  provider: ^6.0.3
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  
  # onesignal
  onesignal_flutter: ^3.0.0

  # firebase
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.8.1
  firebase_remote_config: ^2.0.14
  firebase_messaging: ^13.1.0
  firebase_core_platform_interface: 4.5.1

  # admob
  google_mobile_ads: 2.0.1
  
  # amplitude
  amplitude_flutter: ^3.7.0
  
  # ptich detection
  flutter_audio_capture: ^1.0.0
  pitch_detector_dart: ^0.0.2
  pitchupdart: ^0.0.2
  audioplayers: ^0.20.1

  # network
  http: ^0.13.4
  jwt_decode: ^0.3.1

  # ui
  flutter_svg: ^1.1.0
  flutter_slidable: ^1.3.0
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.1.1
  marquee: ^2.2.3
  animated_text_kit: ^4.2.2
  bubble: ^1.2.1
  toast: ^0.3.0

  # webview
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.4
  youtube_player_iframe: ^3.1.0

  # permission
  app_tracking_transparency: ^2.0.2+4
  permission_handler: ^10.0.0
  in_app_review: ^2.0.4
  
  # db
  path_provider: ^2.0.11
  path: ^1.8.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  flutter_archive: ^5.0.0
  archive: ^3.3.1

  # social
  kakao_flutter_sdk: ^1.2.2
  sign_in_with_apple: ^4.1.0
  flutter_share: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/musics/
    - assets/fitches/
    - assets/musics/recommendation/gender/
    - assets/musics/recommendation/genre/
    - assets/musics/recommendation/popular/
    - assets/musics/recommendation/season/
    - assets/musics/recommendation/tema/
    - assets/config/.env

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.woff2
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.woff2
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.woff2
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.woff2
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.woff2
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.woff2
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.woff2
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.woff2
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.woff2
          weight: 900